# @name get-prompts
GET http://localhost:3333/prompts

###
# @name upload-video
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="example.mp3"
Content-Type: audio/mpeg

< ./tmp/example.mp3j
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
# @name create-transcription
POST http://localhost:3333/videos/2a08f3ec-421a-4140-aff7-40b9071366b3/transcription/
Content-Type: application/json

{
  "prompt": "eminem, lose yourself"
}

###
# @name generate-ai-completion
POST http://localhost:3333/ai/complete/
Content-Type: application/json

{
  "videoId": "2a08f3ec-421a-4140-aff7-40b9071366b3",
  "temperature": 0.5,
  "template": "Gere um resumo sucinto da transcrição do video informada a seguir: '''{{transcription}}'''"
}